Tsm ucf101 ft
PaddlePaddle/PaddleVideo pull request #140
Opened 2021-05-12 13:08 UTC by HydrogenSulfate

1. add tsm_ucf101_frames.yaml and change tsm.yaml to tsm_k400_frames.yaml
2. changes some training settings during finetune in ucf101
3. change the amp settings

2021-05-13 02:53 UTC, huangjun12 requested changes

2021-05-13 02:53 UTC, huangjun12 commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        file_path: "data/k400/k400_train_split_1_rawframes.txt" #Mandatory, train data index file path
k400没有split_1，改成 data/k400_frames/train.list

2021-05-13 02:53 UTC, huangjun12 commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        file_path: "data/k400/k400_val_split_1_rawframes.txt" #Mandatory, valid data index file path
data/k400_frames/val.list

2021-05-13 02:53 UTC, huangjun12 commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        file_path: "data/k400/k400_val_split_1_rawframes.txt" #Mandatory, valid data index file path
data/k400_frames/val.list

2021-05-13 02:53 UTC, huangjun12 commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +#MIX:
这几个注释删了吧

2021-05-13 02:53 UTC, huangjun12 commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        # ls_eps: 0.1 # label smoothing epsilon
这个注释删了吧

2021-05-13 02:53 UTC, huangjun12 commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        values: [0.02, 0.002, 0.0002]  #4 cards * 16 batch size
注释改成 8 cards * 16 batch size

2021-05-13 02:53 UTC, huangjun12 commented on paddlevideo/modeling/heads/tsm_head.py
> +                                               regularizer=L2Decay(1e-4 if num_classes == 400 else 0.0)),
TODO

2021-05-13 02:53 UTC, huangjun12 commented on paddlevideo/tasks/train.py
> +        model_dict = {k: v for k, v in model_dict.items() if 'fc' not in k}
TODO

2021-05-13 02:53 UTC, huangjun12 commented on paddlevideo/tasks/train.py
> +            use_dynamic_loss_scaling=True
同默认参数的不用写了

2021-05-13 02:53 UTC, huangjun12 commented on run.sh
> +
不同数据集的启动脚本不用在run.sh里写了，后面在README文档里补充吧

2021-05-13 02:53 UTC, huangjun12 commented on paddlevideo/tasks/train.py
> +        if weights:
TODO

2021-05-13 02:54 UTC, huangjun12 commented
PR标题不要用简写

2021-05-13 03:14 UTC, HydrogenSulfate commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        file_path: "data/k400/k400_train_split_1_rawframes.txt" #Mandatory, train data index file path
已修改

2021-05-13 03:15 UTC, HydrogenSulfate commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        file_path: "data/k400/k400_val_split_1_rawframes.txt" #Mandatory, valid data index file path
已修改

2021-05-13 03:15 UTC, HydrogenSulfate commented on configs/recognition/tsm/tsm_k400_frames.yaml
> +        file_path: "data/k400/k400_val_split_1_rawframes.txt" #Mandatory, valid data index file path
已修改

2021-05-17 06:11 UTC, huangjun12 requested changes

2021-05-17 06:11 UTC, huangjun12 commented on configs/recognition/tsm/tsm_ucf101_frames.yaml
> +        pretrained: "data/TSM_best.pdparams" #Optional, pretrained model path.
名称改一下吧  TSM_k400.pdparams

2021-05-17 06:11 UTC, huangjun12 commented on paddlevideo/modeling/heads/tsm_head.py
> +        #x = paddle.reshape(x, x.shape[:2])  # [N * seg_num, in_channels]
注释删了

2021-05-17 06:11 UTC, huangjun12 commented on paddlevideo/utils/save_load.py
> +            if not state_dicts.__contains__(name) and state_dicts.__contains__('backbone.' + name):
改成 state_dicts.get(name) ？

2021-05-17 06:11 UTC, huangjun12 commented on configs/recognition/tsm/tsm_nhwc.yaml
>                  short_size: 256
文件名改成 tsm_ucf101_frames_nhwc.yaml，
然后再新增一个配置文件  tsm_k400_frames_nhwc.yaml （暂不用实验验证了）

2021-05-17 06:11 UTC, huangjun12 commented on run.sh
>  #python3.7 -B -m paddle.distributed.launch --gpus="0,1,2,3" --log_dir=log_tsm main.py  --amp --validate -c configs/recognition/tsm/tsm_nhwc.yaml
配置文件改成  tsm_k400_frames_nhwc.yaml

2021-05-17 06:56 UTC, huangjun12 commented on paddlevideo/utils/save_load.py
> +            if state_dicts.get(name) is None and state_dicts.get('backbone.' + name) is not None:
if not state_dicts.get(name)  and state_dicts.get('backbone.' + name):

2021-05-17 07:11 UTC, huangjun12 commented
LGTM

2021-05-17 08:12 UTC, merged