dygraph-to-static benchmark for TSM model
PaddlePaddle/PaddleVideo pull request #219
Opened 2021-10-15 08:52 UTC by 2742195759

## What's New ? 

### 1. 背景

目前 Benchamrk 平台上有静态图、动态图的训练数据监控，缺乏 动转静 @to_static 训练的性能监控，因此在 PaddleVideo 动态图训练代码处进行了动转静支持。

### 2. PR内容

选取 TSM 为例，在 config.yaml 中添加 TO_STATIC字段，并且其中的 enable_to_static = True（缺省则表示False）表示模型开启动转静。如果enable_pass=True表示开启pass策略。

只有当模型存在TO_STATIC字段，并且其中的enable_to_static字段=True的时候才会开启动转静。否则还是保持原来的逻辑。

## 3. 启动样例
```bash
python3.7 -B -u main.py -c /tmp/config.yaml -o epochs=1 -o DATASET.num_workers=8 -o log_interval=5  --amp -o TO_STATIC.enable_to_static=True  -o TO_STATIC.enable_pass=True
```

## 4. 影响面

无，兼容性改进。

2021-10-15 09:50 UTC, Aurelius84 commented on paddlevideo/tasks/train.py
> +def create_input_specs():
移动到 utils 里

2021-10-15 09:50 UTC, Aurelius84 commented on paddlevideo/tasks/train.py
> +    apply_to_static(cfg, model)
考虑下 `-o`传参时  amp 的生效机制，另外添加一下注释，说明下这个是为了benchamrk添加的，默认情况下会跳过

2021-10-20 09:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=219) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=219) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: 2742195759<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleVideo?pullRequest=219) it.</sub>

2021-12-29 02:12 UTC, huangjun12 requested changes

2021-12-29 02:12 UTC, huangjun12 commented on paddlevideo/tasks/train.py
> +            if current_step == cfg.max_iter:
main.py中添加了max_iter参数，无需在配置文件中额外添加

2022-08-03 06:07 UTC, closed without merging