New branch
PaddlePaddle/PaddleVideo pull request #284
Opened 2021-12-17 13:15 UTC by ttjygbtj

交互式视频分割任务的模型Manet

2021-12-17 13:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=284) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleVideo?pullRequest=284) it.</sub>

2021-12-31 08:43 UTC, huangjun12 requested changes
1 整体结构参考CFBI代码重构
2 网络模型与数据dataset代码看是否可以与CFBI复用
3 出了pre-commit的格式检查，不要随意其它模型代码/注释

2021-12-31 08:43 UTC, huangjun12 commented on .gitignore
> +*.csv
`**/.DS_Store/ `改成 `**/.DS_Store`，多了斜杠/

icloud、pdf和csv这三行删了吧，属于自己环境下特有的，提pr前可以先移出

2021-12-31 08:43 UTC, huangjun12 commented on applications/VideoQualityAssessment/paddlevideo/loader/pipelines/augmentations.py
> +        min_size: Lower bound for random batch_sampler.
这里还没有组batch，就用原来的吧，不用修改

2021-12-31 08:43 UTC, huangjun12 commented on docs/en/model_zoo/recognition/pptimesformer.md
> +- [Averaging Weights Leads to Wider Optima and Better Generalization](https://arxiv.org/abs/1803.05407v3), Pavel Izmailov, Dmitrii Podoprikhin, Timur Garipov
不要改其它模型的文档

2021-12-31 08:43 UTC, huangjun12 commented on docs/zh-CN/contribute/how_to_contribute.md
>  upstream    https://github.com/PaddlePaddle/PaddleVideo.git (push)
不要随意修改其它文档

2021-12-31 08:43 UTC, huangjun12 commented on docs/zh-CN/dataset/manet.md
> +# UCF101数据准备
这是UCF-101的数据准备过程？

2021-12-31 08:43 UTC, huangjun12 commented on docs/en/model_zoo/segmentationers/manet.md
> +### Dependencies
写在[requirements](https://github.com/PaddlePaddle/PaddleVideo/blob/develop/requirements.txt)即可

2021-12-31 08:43 UTC, huangjun12 commented on docs/en/model_zoo/segmentationers/manet.md
> + - tensorboardX
tensorboardX是必须的吗？在这个模型中的作用是？

2021-12-31 08:43 UTC, huangjun12 commented on docs/en/model_zoo/segmentationers/manet.md
> + - Pytorch 1.0
为什么还要装pytorch。。。

2021-12-31 08:43 UTC, huangjun12 commented on docs/en/model_zoo/segmentationers/manet.md
> + - davisinteractive (Please refer to [this link](https://interactive.davischallenge.org/user_guide/installation/))
这个是训练还是测试时候用的？还是需要预先安装的工具？

2021-12-31 08:43 UTC, huangjun12 commented on main.py
> +                               train_model_multigrid, train_model_multistage)
别加这个了 train_model_multistage

2021-12-31 08:43 UTC, huangjun12 commented on main.py
> +    elif args.multistage:
两个train脚本启动2次吧，现阶段先别加这个了

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/loader/builder.py
> +    cfg_dataset['pipeline'] = build_pipeline(cfg_pipeline)
这个修改是？

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/loader/builder.py
> +        batch_sampler = BatchSampler(dataset,
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/BatchSampler_cn.html#batchsampler 是单卡使用的，多卡使用DistributedBatchSampler。这里看起来没必要自己重新写一个build Sampler，用原来的就可以？

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/loader/dataloader/manet_dataloader.py
> +from .base import BaseDataLoader
为什么要重新build dataloader类，用现有的不可以吗？

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/loader/dataset/davis_2017_f.py
> +        return self.prepare_test(idx)
```
return self.prepare_train(idx)
```
?

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/loader/dataset/davis_2017_f.py
> +class DAVIS2017_TrainDataset(BaseDataset):
重复代码尽可能复用，不要创建这么多Dataset类

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/modeling/backbones/aspp_manet.py
> +class ASPP(nn.Layer):
看下与CFBI模型代码是否可以复用

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/modeling/backbones/deeplab_manet.py
> +class FrozenBatchNorm2d(nn.Layer):
看下与CFBI代码是否可以复用

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/modeling/backbones/resnet_tsm.py
> +        #  1. the phase of generating data[images, label] from batch_sampler
dataloader -> batch_sampler 这类注释修改都改回去吧

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/modeling/builder.py
> +def build_segmentationer(cfg, train_cfg=None, test_cfg=None):
复用CFBI现有的

2021-12-31 08:43 UTC, huangjun12 commented on paddlevideo/modeling/framework/partitioners/transnetv2_partitioner.py
> +    def test_step(self, data_batch):
不要随意修改其它模型代码

2021-12-31 08:43 UTC, huangjun12 commented on configs/segmentationer/manet_stage1.yaml
> +TRAIN: #TRAIN
不要这个字段

2021-12-31 08:43 UTC, huangjun12 commented on configs/segmentationer/manet_stage1.yaml
> +DATALOADER:
不要这个字段

2022-01-01 04:43 UTC, ttjygbtj commented on paddlevideo/loader/dataloader/manet_dataloader.py
> +from .base import BaseDataLoader
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66538098/147844170-24721072-4a25-4a18-9b0b-9d97bf681a17.png">
我是忠实的照着原作者的代码改的，他有自定义dataloader

2022-01-01 04:45 UTC, ttjygbtj commented on paddlevideo/loader/builder.py
> +        batch_sampler = BatchSampler(dataset,
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66538098/147844181-4fc6f90b-cda7-423e-8f8d-9c69f75b414f.png">
我是忠实的照着原作者的代码改的，他有自定义Sampler

2022-01-01 04:45 UTC, ttjygbtj commented on main.py
> +    elif args.multistage:
已经改成两个脚本了，OK

2022-01-01 04:45 UTC, ttjygbtj commented on main.py
> +                               train_model_multigrid, train_model_multistage)
已经改成两个脚本了，OK

2022-01-01 04:46 UTC, ttjygbtj commented on docs/en/model_zoo/segmentationers/manet.md
> + - Pytorch 1.0
好的我错了，已经删除了

2022-01-01 04:47 UTC, ttjygbtj commented on docs/en/model_zoo/segmentationers/manet.md
> + - davisinteractive (Please refer to [this link](https://interactive.davischallenge.org/user_guide/installation/))
davisinteractive是test时用到的工具包

2022-01-01 04:47 UTC, ttjygbtj commented on docs/en/model_zoo/segmentationers/manet.md
> + - tensorboardX
不用，已经删除了

2022-01-01 04:47 UTC, ttjygbtj commented on docs/en/model_zoo/segmentationers/manet.md
> +### Dependencies
好

2022-01-01 04:48 UTC, ttjygbtj commented on applications/VideoQualityAssessment/paddlevideo/loader/pipelines/augmentations.py
> +        min_size: Lower bound for random batch_sampler.
好

2022-01-01 04:48 UTC, ttjygbtj commented on .gitignore
> +*.csv
好

2022-01-01 04:48 UTC, ttjygbtj commented on paddlevideo/loader/builder.py
> +    cfg_dataset['pipeline'] = build_pipeline(cfg_pipeline)
我改回去了。都是可以的。

2022-01-01 04:50 UTC, ttjygbtj commented on paddlevideo/loader/dataset/davis_2017_f.py
> +class DAVIS2017_TrainDataset(BaseDataset):
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66538098/147844232-6a3bcef8-394c-44e9-bc52-03fb83e22fc8.png">
我是忠实的照着原作者的代码改的，他有自定义好几种dataset

2022-01-01 05:53 UTC, ttjygbtj commented on paddlevideo/modeling/backbones/resnet_tsm.py
> +        #  1. the phase of generating data[images, label] from batch_sampler
嗯嗯，所有其他模型相关的我都不动

2022-01-01 05:57 UTC, ttjygbtj commented on paddlevideo/modeling/backbones/aspp_manet.py
> +class ASPP(nn.Layer):
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/66538098/147844870-2804c564-9d80-412b-a07e-32bd88ad8e46.png">
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/66538098/147844881-da6c7789-75ac-4cc5-a3f6-96d3f4bb9bb9.png">

manet的aspp和cfbi的部分不同如上，是不是不太能复用？

2022-01-10 03:16 UTC, huangjun12 commented on .gitignore
> -__pycache__/
这个保留

2022-01-10 03:16 UTC, huangjun12 commented on .gitignore
> +**/*.jpg
为什么要添加这两个

2022-01-10 03:16 UTC, huangjun12 commented on .log.txt
> +[12/23 18:32:11] DALI is not installed, you can improve performance if use DALI
删除隐藏的日志文件

2022-01-10 03:16 UTC, huangjun12 commented on configs/segmentation/manet_stage1.yaml
> +#epochs: 674 #Mandatory, total epoch
删除多余的注释

2022-01-10 03:16 UTC, huangjun12 commented on configs/segmentation/manet_stage2.yaml
> +#    file_path: "/home/lc/manet/data/DAVIS" #Mandotary, test data index file path.
删除多余的注释

2022-01-10 03:16 UTC, huangjun12 commented on data/ava/script/fetch_ava_proposals.sh
> -#!/usr/bin/env bash
不要删除其它模型的代码

2022-01-10 03:16 UTC, huangjun12 commented on data/yt8m/tf2pkl.py
> -#  Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserve.
不要删除data目录下的内容

2022-01-10 03:16 UTC, huangjun12 commented on docs/zh-CN/model_zoo/segmentation/manet.md
> +# Ma-Net视频切分模型
MA or Ma？

2022-01-10 03:16 UTC, huangjun12 commented on main.py
> +# Unless requifFred by applicable law or agreed to in writing, software
这个修改是。。。

2022-01-18 10:54 UTC, HydrogenSulfate commented on .github/ISSUE_TEMPLATE/bug_report 2.md
> +---
这几个文件如果与PR本身无关，建议去掉。

2022-01-18 10:54 UTC, HydrogenSulfate commented on .github/ISSUE_TEMPLATE/custom 2.md
> +---
同上

2022-01-18 10:54 UTC, HydrogenSulfate commented on .github/ISSUE_TEMPLATE/feature_request 2.md
> +---
同上

2022-01-18 10:56 UTC, HydrogenSulfate commented on configs/segmentation/manet_stage1.yaml
> +    #    pretrained: "/root/codespace/manet_paddle/init_for_align.pdparams"
冗余的注释可以去掉

2022-01-18 11:06 UTC, HydrogenSulfate commented on docs/zh-CN/tutorials/reletive_issues 2
> +video_path is what ? #4510
该文件与PR有关吗，无关的话也可以去掉

2022-01-18 11:23 UTC, HydrogenSulfate commented on paddlevideo/loader/pipelines/custom_transforms_f.py
> +                tmp /= (0.229, 0.224, 0.225)
建议将mean和std仿照Normalization类，以传入参数的形式使用，尽量不要硬编码到代码文件中

2022-01-18 11:35 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/aspp_manet.py
> +from paddlevideo.utils.manet_utils import kaiming_normal_
应该可以复用ADDS的kaiming_normal_，在PaddleVideo/paddlevideo/modeling/weight_init.py下有

2022-01-18 11:36 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/aspp_manet.py
> +        return self.dropout(x)
两个return，留下一个正确的。

2022-01-18 11:38 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/aspp_manet.py
> +        self._init_weight()
backbone的_init_weight会在framework里被调用，因此最好仿照其他模型，改成同样的名字，然后在framework调用

2022-01-18 11:43 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/aspp_manet.py
> +                zero_(m.bias)
建议将fill_和zeros_改成https://github.com/PaddlePaddle/PaddleVideo/blob/develop/paddlevideo/modeling/backbones/vit.py#L30的形式

2022-01-18 13:31 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/decoder_manet.py
> +                zero_(m.bias)
同上

2022-01-18 13:33 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/deeplab_manet.py
> +    print(output.shape)
调试代码可以删掉

2022-01-18 13:35 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/resnet_manet.py
> +        return self.sublayers()
为什么要返回sublayers()呢？

2022-01-18 13:37 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/resnet_manet.py
> +    return ResNet101(output_stride, BatchNorm, pretrained)
backbone的构建由framework中调用builder.build_backbone(backbone)得到，不需要在backbone内加入build代码，建议重构一下

2022-01-18 13:38 UTC, HydrogenSulfate commented on paddlevideo/modeling/backbones/resnet_manet.py
> +        json.dump(low_level_feat.tolist(), f)
调试代码删掉

2022-01-18 13:40 UTC, HydrogenSulfate commented on paddlevideo/modeling/framework/segment/base.py
> +    def forward(self, data_batch, mode='infer', train_cfg=None, **kwargs):
train_cfg可以由self.train_cfg得到，是不是可以不需要作为参数传入？

2022-01-18 13:47 UTC, HydrogenSulfate commented on paddlevideo/modeling/framework/segment/manet_stage2.py
> +        inter_file.close()
framework的代码一般用于定义模型整体，包含backbone和head即可，训练和测试代码建议重构一下，合并到train.py和test.py中去

2022-01-18 13:48 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +"""
调试代码可以删掉

2022-01-18 13:52 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +
注释代码删掉

2022-01-18 13:52 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +    #     print(prev_frame_labels.place, prev_frame_embedding.place, query_embedding.place)
注释代码删掉

2022-01-18 13:53 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +from ..registry import HEADS
import语句建议移动到文件开头位置

2022-01-18 13:54 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +                # nn_features_n = nn_features_n.detach()
注释代码删掉

2022-01-18 13:54 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +            #             print(prev_frame_nn_features_n.mean().item(), prev_frame_nn_features_n.shape, interaction_num)  # o
注释代码删掉

2022-01-18 13:55 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +                # prev_frame_nn_features_n = prev_frame_nn_features_n.detach()
注释代码删掉

2022-01-18 13:55 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +            # nn_features_n_ = nn_features_n_.detach()
注释代码删掉

2022-01-18 13:55 UTC, HydrogenSulfate commented on paddlevideo/modeling/heads/IntVOS.py
> +            )  # float comparision?
不相关的注释代码删掉

2022-01-18 13:57 UTC, HydrogenSulfate commented on paddlevideo/modeling/losses/manet_loss.py
> +class Added_CrossEntropyLoss(BaseWeightedLoss):
名字是否可以改成更准确一点的，比如Topk_CrossEntropyLoss

2022-01-18 13:58 UTC, HydrogenSulfate commented on paddlevideo/solver/lr.py
> +        cfg_copy['lr_lambda'] = eval(cfg_copy['lr_lambda'])
Lambda LR paddle应该有对应API：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/LambdaDecay_cn.html#lambdadecay，是否可以用官方API代替而不是自己写一个？

2022-01-18 14:09 UTC, HydrogenSulfate commented on paddlevideo/solver/optimizer.py
> +                for n in params:
mm和m可以改用易懂的命名，mm->unit_dict, m->unit_name, params->unit_params

2022-01-18 14:17 UTC, HydrogenSulfate commented on paddlevideo/tasks/test.py
> +
如果MANet的test过程和其他模型不同，可以暂时写在`if cfg.MODEL.framework == "ManetSegment_Stage2":`条件下，其余的情况放在在else下面\

2022-01-18 14:42 UTC, HydrogenSulfate commented on paddlevideo/tasks/train.py
>  from ..loader.builder import build_dataloader, build_dataset
可以新建一个train_manet.py，把MANet的代码迁移到里面

2022-01-18 14:45 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +            tot += 1
注释可以删掉

2022-01-18 14:45 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +    # print('%d num_batches_tracked skipped' % tot)
注释可以删掉

2022-01-18 14:46 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +        self.avg = self.sum / self.count
可以复用`paddlevideo/utils/record.py`的AverageMeter

2022-01-18 14:48 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +    return input
转换代码可以不用写

2022-01-18 14:50 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +def clip_grad_norm_(parameters: _tensor_or_tensors,
Momentum优化器支持gradclip，传入参数即可，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/Momentum_cn.html#momentum
如果该函数没有使用到，可以删掉

2022-01-18 14:51 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +# def max(a: paddle.Tensor, axis=0, keepdim=True):
注释可以删掉

2022-01-18 14:53 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +def _no_grad_trunc_normal_(tensor, mean, std, a, b):
在`paddlevideo/modeling/weight_init.py`有trunc_normal_的实现，可以复用一下

2022-01-18 14:54 UTC, HydrogenSulfate commented on paddlevideo/utils/manet_utils.py
> +# sparse = _make_deprecate(sparse_)
注释删掉

2022-01-18 14:57 UTC, HydrogenSulfate commented on paddlevideo/utils/record.py
> +def log_batch(metric_list, batch_id, epoch_id, total_epoch, mode, ips, tot_step=None,max_iters=None):
tot_step->step_id, max_iters->total_step

2022-01-18 15:21 UTC, HydrogenSulfate commented on paddlevideo/loader/builder.py
> +        batch_sampler = BatchSampler(dataset,
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/66538098/147844181-4fc6f90b-cda7-423e-8f8d-9c69f75b414f.png">
> 
> 我是忠实的照着原作者的代码改的，他有自定义Sampler

可以在`paddlevideo/loader/builder.py`里的`build_dataloader`函数，通过kwargs参数控制是否构建RandomIdentitySampler，然后paddle的dataloader没有sampler，只有batch_samper的问题，可以通过sampler来初始化一个batch_sampler，再传给DataLoader使用

2022-01-20 04:39 UTC, ttjygbtj commented on paddlevideo/loader/pipelines/custom_transforms_f.py
> +                tmp /= (0.229, 0.224, 0.225)
但是这个类对不同维度张量会有不同处理，在一次运行train时不同维度的张量都会出现
<img width="455" alt="image" src="https://user-images.githubusercontent.com/66538098/150274522-cf819f77-eb52-4c81-8fe1-de76e6dd6219.png">

2022-01-20 05:34 UTC, ttjygbtj commented on paddlevideo/modeling/backbones/resnet_manet.py
> +    return ResNet101(output_stride, BatchNorm, pretrained)
back_bone不是resnet，resnet是backbone的backbone

2022-01-20 05:37 UTC, ttjygbtj commented on paddlevideo/modeling/framework/segment/manet_stage2.py
> +        inter_file.close()
您好，stage2这里包括test和军哥讨论过了，这里是两重循环，train是一重循环。stage2只好这样写。

2022-01-20 06:06 UTC, ttjygbtj commented on paddlevideo/solver/lr.py
> +        cfg_copy['lr_lambda'] = eval(cfg_copy['lr_lambda'])
这里就是调用官方的，但是lambda总得自己传进去呢

2022-01-20 06:06 UTC, ttjygbtj commented on paddlevideo/solver/optimizer.py
> +                for n in params:
嗯呐

2022-01-20 06:08 UTC, ttjygbtj commented on paddlevideo/tasks/train.py
>  from ..loader.builder import build_dataloader, build_dataset
第一次提pr我就是train_multistage被否决了说比较复杂。现在是第三四次pr

2022-01-21 10:48 UTC, huangjun12 commented
refer to #346

2022-01-21 10:48 UTC, closed without merging