Add evaluate and test code for SlowFast_FasterRCNN based on AVA dataset
PaddlePaddle/PaddleVideo pull request #290
Opened 2021-12-22 08:39 UTC by XYZ916829

SlowFast+FasterRCNN模型新增评估和测试代码以及中英文docs

2021-12-22 08:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=290) before we can accept your contribution.<br/><hr/>**XYZ916829** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleVideo?pullRequest=290) it.</sub>

2021-12-29 08:17 UTC, huangjun12 requested changes
remove .DS_Store

2021-12-29 08:17 UTC, huangjun12 commented on configs/detection/ava/ava.yaml
> +    action_thr: 0.0
DATASET前加个空行， 便于查看

2021-12-29 08:17 UTC, huangjun12 commented on configs/detection/ava/ava.yaml
> +PIPELINE:
加个空行

2021-12-29 08:17 UTC, huangjun12 commented on configs/detection/ava/ava.yaml
> +OPTIMIZER: #OPTIMIZER field
加个空行

2021-12-29 08:17 UTC, huangjun12 commented on configs/detection/ava/ava.yaml
> +model_name: AVA_SlowFast_FastRcnn
加个空行

2021-12-29 08:17 UTC, huangjun12 commented on data/ava/script/extract_video_frames.sh
> +o "帧保存路径$1"
显示内容改成英文吧

2021-12-29 08:17 UTC, huangjun12 commented on docs/zh-CN/model_zoo/detection/SlowFast_FasterRCNN.md
> +我们提供了详尽理论及代码讲解，并可使用免费在线GPU算力资源，一键运行的AI Studio Notebook项目，使用链接：[基于SlowFast+FasterRCNN的动作识别](./)
还没有的话 这句可以先不写

2021-12-29 08:17 UTC, huangjun12 commented on paddlevideo/modeling/framework/detectors/two_stage.py
> +    # 模型推理
尽量用英文注释

2021-12-29 08:17 UTC, huangjun12 commented on main.py
> +    parser.add_argument('--valid',
已有`validate`参数的功能是指定是否开启valid功能，不用再额外添加？
如果这里是想实现测试功能，可以使用`paddlevideo/tasks/test.py`

2021-12-29 08:17 UTC, huangjun12 commented on docs/zh-CN/model_zoo/detection/SlowFast_FasterRCNN.md
> +- [模型测试](#模型测试)
训练、测试、推理？
格式参考：https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/pp-tsm.md

2021-12-29 08:17 UTC, huangjun12 commented on tools/infer.py
> +    args = parse_args() #解析参数
这是python端的推理吗？
目前的推理都是先export-model，再通过`tools/predict.py`实现

2021-12-29 08:33 UTC, XYZ-916 commented on main.py
> +    parser.add_argument('--valid',
这里的validate参数貌似是训练的时候是否启用评估，后来加的valid参数是只评估不训练。

2021-12-30 02:01 UTC, XYZ-916 commented on tools/infer.py
> +    args = parse_args() #解析参数
是python端推理，目前export-model还有些问题没有解决

2022-01-12 12:10 UTC, huangjun12 commented on main.py
> +    parser.add_argument('--valid',
这行删一下？

2022-01-12 12:10 UTC, huangjun12 commented on tools/export_model.py
> +            InputSpec(shape=[None, None, 4], dtype='float32', name='proposals'),
两个None，确认可以正常跑嘛

2022-01-13 01:55 UTC, XYZ-916 commented on tools/export_model.py
> +            InputSpec(shape=[None, None, 4], dtype='float32', name='proposals'),
> 两个None，确认可以正常跑嘛

可以的

2022-01-13 15:47 UTC, huangjun12 commented
LGTM

2022-01-13 15:47 UTC, merged