fix footballaction bug
PaddlePaddle/PaddleVideo pull request #361
Opened 2022-02-14 07:55 UTC by ZhangHandi

1. fix FootballAction bug
2. modify readme

2022-02-14 11:48 UTC, huangjun12 requested changes

2022-02-14 11:48 UTC, huangjun12 commented on applications/FootballAction/README.md
> -### 基础镜像
这个保留吧

2022-02-14 11:48 UTC, huangjun12 commented on applications/FootballAction/README.md
> +        feat = self.avgpool2d(feature)
__init__里需要添加`self.avgpool2d = xxx`

2022-02-14 11:48 UTC, huangjun12 commented on applications/FootballAction/predict/action_detect/models/pptsm_infer.py
> +        self.output_tensor = self.predictor.get_output_handle(output_names[0])
这个修改是？

2022-02-14 11:48 UTC, huangjun12 commented on applications/FootballAction/datasets/script/get_instance_for_bmn.py
> +        feature = pickle.load(open(feat_path, 'rb'))
这是默认加上了音频特征？

2022-02-14 11:48 UTC, huangjun12 commented on applications/FootballAction/datasets/script/get_instance_for_bmn.py
> +    with open('temp.json', 'w', encoding='utf-8') as f:
这个打开的作用是？

2022-02-14 14:36 UTC, muare commented on applications/FootballAction/predict/action_detect/models/pptsm_infer.py
> +        self.output_tensor = self.predictor.get_output_handle(output_names[0])
是不是因为在 Recognizer2D 的 infer_step，修改为只返回 feat，所以这里的output_names就只有一个那。另外，目前通过 checkpoint 目录里面的download.txt下载的 ppTSM 预训练模型，具有 class score和feat两个输出。我也在 issue 里面提那一个 ticket，请教这个问题 #360

2022-02-16 03:11 UTC, ZhangHandi commented on applications/FootballAction/datasets/script/get_instance_for_bmn.py
> +    with open('temp.json', 'w', encoding='utf-8') as f:
这个删掉了

2022-02-16 03:12 UTC, ZhangHandi commented on applications/FootballAction/datasets/script/get_instance_for_bmn.py
> +        feature = pickle.load(open(feat_path, 'rb'))
对的，之前的只有图像特征

2022-02-16 05:49 UTC, ZhangHandi commented on applications/FootballAction/predict/action_detect/models/pptsm_infer.py
> +        self.output_tensor = self.predictor.get_output_handle(output_names[0])
是的，infer_step 修改后只返回feature，output_names就只有一个了

2022-02-17 11:48 UTC, huangjun12 reviewed
(1) 文档最开始位置加一个目录
(2) 文档顺序改一下：先说怎么推理，再讲训练吧

2022-02-17 11:48 UTC, huangjun12 commented on applications/FootballAction/README.md
> -```
这两个```符号不用删了，是bash命令

2022-02-17 11:48 UTC, huangjun12 commented on applications/FootballAction/README.md
>  ####  step1.4  基于ppTSM的视频特征提取
基于PP-TSM

2022-02-22 06:25 UTC, huangjun12 commented
LGTM

2022-02-22 06:25 UTC, merged