refine requirements.txt & fix T2VLAD bugs & refine doc links
PaddlePaddle/PaddleVideo pull request #370
Opened 2022-02-25 04:58 UTC by HydrogenSulfate

1. 简化了不必要的依赖项，使用try-except机制提示可能缺少的包，卸载matplotlib后PP-TSM推理仍然能运行，如下图所示
![image](https://user-images.githubusercontent.com/23737287/155656344-b87afa3a-75bf-499f-a953-dec30160ad6d.png)
2. 修复T2VLAD代码bug
3. 涉及到的所有文档开头加入环境安装提示。

2022-02-28 03:01 UTC, huangjun12 reviewed
CI挂了，还得再修一下

2022-02-28 12:00 UTC, huangjun12 requested changes

2022-02-28 12:00 UTC, huangjun12 commented on applications/EIVideo/EIVideo/README.MD
> +在开始使用之前，您可能需要按照以下命令安装额外的依赖包：
去掉`可能`

2022-02-28 12:00 UTC, huangjun12 commented on applications/EIVideo/EIVideo/docs/en/manet.md
> +Before getting started, you may need to install additional dependencies as follows:
move `may`

2022-02-28 12:00 UTC, huangjun12 commented on applications/Ma-Net/utils/mask_damaging.py
> +    print(f"{e}, [scikit-image] package and it's dependencies may needed.")
报错信息打印一下在哪里用的吧 

```python
print(f"{e}, [scikit-image] package and it's dependencies is required for MA-Net.")
```

2022-02-28 12:00 UTC, huangjun12 commented on paddlevideo/loader/pipelines/decode_image.py
> -import skimage.transform
`skimage`这个比较常用，也保留吧

2022-02-28 13:18 UTC, HydrogenSulfate commented on paddlevideo/loader/pipelines/decode_image.py
> -import skimage.transform
Done

2022-02-28 13:18 UTC, HydrogenSulfate commented on applications/Ma-Net/utils/mask_damaging.py
> +    print(f"{e}, [scikit-image] package and it's dependencies may needed.")
Done

2022-02-28 13:18 UTC, HydrogenSulfate commented on applications/EIVideo/EIVideo/docs/en/manet.md
> +Before getting started, you may need to install additional dependencies as follows:
Done

2022-02-28 13:21 UTC, HydrogenSulfate commented on applications/EIVideo/EIVideo/README.MD
> +在开始使用之前，您可能需要按照以下命令安装额外的依赖包：
Done

2022-03-01 02:25 UTC, huangjun12 commented
LGTM

2022-03-01 02:25 UTC, merged