add the configs and documentation of FFA-Net
PaddlePaddle/PaddleVideo pull request #412
Opened 2022-04-16 11:06 UTC by bitcjm

2022-04-19 11:05 UTC, huangjun12 requested changes

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +在此非常感谢：[zhilin007](https://github.com/zhilin007)贡献的FFA-NET repo，提高了本repo复现论文的效率。
这一部分删除

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +##  [FFA-Net: Feature Fusion Attention Network for Single Image Dehazing](https://arxiv.org/abs/1911.07559) (AAAI 2020)
参考论文放在最后 文档格式参考 https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/pp-tsm.md

包括：
[模型简介]
[数据准备]
[模型训练]
[模型测试]
[模型推理]
*[tipc说明]
[参考论文]

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +作者使用了两种注意力块，达到两种不同的目的。一种是通道注意力块，如图1左上所示，假设该注意力块输入特征层尺寸为(1,64,256,256)，经过层池化、卷积等操作，最后进行Sigmoid激活，输出一个尺寸为(1,64,1,1)的中间结果，之后与输入相乘，得到该注意力块的输出，这样就对每个通道乘以了不同的权重(0-1之间)，产生了注意力效果。另一种是像素注意力块，假设该注意力块输入特征层尺寸为(1
简介几句话概括核心思想即可

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +**示例**
示例放在推理部分吧

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +## 2、数据集说明及复现精度
新建一个数据集文档吧

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +  注：能正常运行paddleVideo即可正常运行本模型
这部分不用单独写了

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +- `-o`: 指定重写参数，例如： `-o DATASET.batch_size=16` 用于重写train时batch size大小
PaddleVideo使用文档有说明，可以不用在这里重复写了

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +### 4.3 恢复训练
这个也不用

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +### 4.4 模型评估
用表格列一下精度吧

2022-04-19 11:05 UTC, huangjun12 commented on docs/zh-CN/model_zoo/estimation/ffa_ch.md
> +## 5、代码结构说明
这部分也不用了

2022-04-19 11:05 UTC, huangjun12 commented on paddlevideo/modeling/backbones/ffa_net.py
> +@BACKBONES.register()
不用每个类都注册
在FFA类前加装饰器注册即可

2022-04-19 11:05 UTC, huangjun12 commented on paddlevideo/modeling/framework/generator/ffa_metrics.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
这个metric跟 paddlevideo/metrics/ffa_metric.py 是一样的吗？是否能够直接import呢

2022-04-19 11:05 UTC, huangjun12 commented on tools/predict.py
> +    if model_name == 'FFA':
看起来不用加这个分支，走最后的else分支即可？

2022-04-24 10:48 UTC, huangjun12 requested changes

2022-04-24 10:48 UTC, huangjun12 commented on paddlevideo/loader/dataset/ffa_dataset.py
> +        id = path.split('\\')[-1].split('_')[0]
同上

2022-04-24 10:48 UTC, huangjun12 commented on paddlevideo/loader/dataset/ffa_dataset.py
> +        id = path.split('\\')[-1].split('_')[0]
linux系统下，改为
```python
path.split('/')[-1].split('_')[0]
```
可以判断一下系统，或者默认用linux的方式

2022-04-24 10:48 UTC, huangjun12 commented on tools/utils.py
> +        id = path.split('\\')[-1].split('_')[0]
同上

2022-04-24 10:48 UTC, huangjun12 commented on test_tipc/configs/FFA/train_infer_python.txt
> +norm_train:main.py -c configs/estimation/adds/FFA_cfg.yaml --seed 1234 --validate -o DATASET.train.file_path="data/FFA/FFA_lite_data" -o DATASET.valid.file_path="data/FFA/FFA_lite_data"
data/FFA/FFA_lite_data 这个数据需要上传一下

2022-04-25 07:26 UTC, huangjun12 commented on test_tipc/prepare.sh
> +        wget -nc -P https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ITS2_3_19_400000_transform.pdparams
```bash
wget -nc -P ./data https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ITS2_3_19_400000_transform.pdparams
```

2022-04-25 07:26 UTC, huangjun12 commented on test_tipc/configs/FFA/train_infer_python.txt
> +--use_tensorrt:False|True
目前cpu、tensorRT、batch_size=2几种情况跑不通(非必需，可先不修)

41行到45行修改一下

```txt
--use_gpu:True
--enable_mkldnn:False
--cpu_threads:1
--batch_size:1
--use_tensorrt:False
```

2024-03-05 03:01 UTC, jerrywgz commented
感谢贡献，目前代码库暂不新增功能支持，PR先关闭了

2024-03-05 03:01 UTC, closed without merging