add paddle2onnx for PP-TSN
PaddlePaddle/PaddleVideo pull request #417
Opened 2022-04-26 06:11 UTC by HydrogenSulfate

1. PP-TSN增加paddle2onnx，onnx推理，以及对应文档

2022-05-05 08:10 UTC, huangjun12 requested changes

2022-05-05 08:10 UTC, huangjun12 commented on tools/predict.py
> +
新建一个文件 onnx.py？

2022-05-05 13:47 UTC, HydrogenSulfate commented on tools/predict.py
> +
Done

2022-05-06 02:13 UTC, huangjun12 commented on tools/predict_onnx.py
> +if __name__ == "__main__":
这个文件也放到 paddle2onnx文件夹下？

2022-05-06 03:38 UTC, HydrogenSulfate commented on tools/predict_onnx.py
> +if __name__ == "__main__":
Done

2022-05-24 03:22 UTC, huangjun12 requested changes

2022-05-24 03:22 UTC, huangjun12 commented on tools/utils.py
> +                 num_seg: int = 8,
这部分类型注解，是IDE自动修改的吗

似乎没太有必要加？对于小白可读性也不强

2022-05-24 03:22 UTC, huangjun12 commented on deploy/paddle2onnx/predict_onnx.py
> +    if model_name in ["MSTCN", "ASRF"]:
这一行删了？

2022-05-25 02:05 UTC, merged