add cpp serving for PP-TSM
PaddlePaddle/PaddleVideo pull request #425
Opened 2022-05-10 04:57 UTC by HydrogenSulfate

1. 增加PP-TSM模型的CPP serving功能和对应文档

2022-05-27 03:13 UTC, huangjun12 requested changes

2022-05-27 03:13 UTC, huangjun12 commented on deploy/cpp_serving/readme.md
> +使用 PaddleServing 做服务化部署时，需要将保存的 inference 模型转换为 Serving 模型。下面以 PP-TSM 模型为例，介绍如何部署动作分类服务。
参考https://github.com/PaddlePaddle/PaddleVideo/pull/368这个pr对应位置改下细节吧

2022-05-27 03:13 UTC, huangjun12 commented on deploy/cpp_serving/readme.md
> +  PaddleVideo
参考 https://github.com/PaddlePaddle/PaddleVideo/pull/368 这个pr对应位置改下细节吧

2022-05-27 03:13 UTC, huangjun12 commented on deploy/cpp_serving/readme.md
> +  PaddleVideo
参考 https://github.com/PaddlePaddle/PaddleVideo/pull/368 这个pr对应位置改下细节吧

2022-05-27 03:13 UTC, huangjun12 commented on deploy/cpp_serving/readme.md
> +  pipeline_http_client.py     # client端发送数据并获取预测结果的脚本
说明下各文件含义
serving_client.py 
preprocess_ops.py
paddle_env_install.sh
xxx

2022-05-27 03:13 UTC, huangjun12 commented on deploy/cpp_serving/readme.md
> +  pipeline_http_client.py     # client端发送数据并获取预测结果的脚本
说明下个文件含义
serving_client.py 
preprocess_ops.py
paddle_env_install.sh
xxx

2022-05-27 03:13 UTC, huangjun12 commented on deploy/cpp_serving/serving_client.py
> +def np_softmax(x: np.ndarray, axis=-1) -> np.ndarray:
axis默认值是0？

2022-05-27 03:13 UTC, huangjun12 commented on deploy/cpp_serving/serving_client.py
> +def np_softmax(x: np.ndarray, axis=-1) -> np.ndarray:
axis默认值是0？

2022-05-27 12:33 UTC, HydrogenSulfate commented on deploy/cpp_serving/readme.md
> +使用 PaddleServing 做服务化部署时，需要将保存的 inference 模型转换为 Serving 模型。下面以 PP-TSM 模型为例，介绍如何部署动作分类服务。
Done

2022-05-27 12:33 UTC, HydrogenSulfate commented on deploy/cpp_serving/readme.md
> +  PaddleVideo
Done

2022-05-27 12:33 UTC, HydrogenSulfate commented on deploy/cpp_serving/readme.md
> +  PaddleVideo
Done

2022-05-27 12:33 UTC, HydrogenSulfate commented on deploy/cpp_serving/readme.md
> +  pipeline_http_client.py     # client端发送数据并获取预测结果的脚本
Done

2022-05-27 12:33 UTC, HydrogenSulfate commented on deploy/cpp_serving/readme.md
> +  pipeline_http_client.py     # client端发送数据并获取预测结果的脚本
Done

2022-05-27 12:33 UTC, HydrogenSulfate commented on deploy/cpp_serving/serving_client.py
> +def np_softmax(x: np.ndarray, axis=-1) -> np.ndarray:
已从-1改为0

2022-05-30 02:26 UTC, huangjun12 commented
LGTM

2022-05-30 02:26 UTC, merged