paddlevideo/modeling/backbones/__init__.py
PaddlePaddle/PaddleVideo pull request #437
Opened 2022-05-23 08:28 UTC by chaineypung

将TCANet++网络名添加到init中

2022-05-23 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=437) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: test<br/>:x: chaineypung<br/><hr/>**test** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleVideo?pullRequest=437) it.</sub>

2022-06-07 07:46 UTC, huangjun12 requested changes

2022-06-07 07:46 UTC, huangjun12 commented on .pre-commit-config.yaml
> +    -   id: yapf
这个文件可以不用改动～

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/configs/localization/tcanetpp.yaml
> +MODEL: #MODEL field
文件命名改成pp-tcanet.yaml吧

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/configs/localization/tcanetpp.yaml
> +        name: "TCANetpp"
改成ppTCVNet

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/configs/localization/tcanetpp.yaml
> +# OPTIMIZER: #OPTIMIZER field
请删除冗余注释

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/requirements.txt
> +SimpleITK
requirements可以简化一下？paddlenlp、SimpleITK等这个模型应该用不到吧

2022-06-07 07:46 UTC, huangjun12 commented on paddlevideo/modeling/backbones/__init__.py
> +from .TCANetpp import TCANetplusplus
TCANetplusplus名字太长了，都统一改成ppTCANet吧

2022-06-07 07:46 UTC, huangjun12 commented on paddlevideo/modeling/backbones/TCANetplusplus.py
> +class TCANetpp(paddle.nn.Layer):
ppTCANet

2022-06-07 07:46 UTC, huangjun12 commented on paddlevideo/modeling/backbones/TCANetplusplus.py
> +    """BMN model from
注释改一下吧

2022-06-07 07:46 UTC, huangjun12 commented on paddlevideo/modeling/backbones/TCANetplusplus.py
> +def get_interp1d_mask(tscale, dscale, prop_boundary_ratio, num_sample,
这个函数可以从BMN里面import吗

2022-06-07 07:46 UTC, huangjun12 commented on paddlevideo/modeling/backbones/TCANetplusplus.py
> +def _get_interp1d_bin_mask(seg_xmin, seg_xmax, tscale, num_sample,
这个函数可以从BMN里面import吗

2022-06-07 07:46 UTC, huangjun12 commented on paddlevideo/loader/pipelines/anet_pipeline.py
> +            for jdx in range(1, 50 + 1):
兼容性修改哈， 50可以改成self.tscale从外部传入？

2022-06-07 07:46 UTC, huangjun12 commented on paddlevideo/loader/dataset/bmn_dataset.py
> +        multiply_noise = np.random.normal(loc=1.0, scale=0.05,
加一个参数进行分支控制吧，尽量不要影响原始BMN的使用

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/tools/utils.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
是否可以删除一些与本模型无关的部分呢

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/tools/predict.py
> +# def main():
删除冗余注释

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/tools/predict.py
> +    if model_name == 'TransNetV2':
没有用到的分支可以删除

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/tools/paddlevideo_clas.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
这个文件应该可以直接删除？

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/tools/export_model.py
> +    if model_name in ['ppTSM', 'TSM']:
删除没有用到的分支

2022-06-07 07:46 UTC, huangjun12 commented on applications/TCANet++/configs/example.yaml
> +MODEL: #MODEL field
这个配置文件，是否可以删除呢

2024-03-05 03:01 UTC, jerrywgz commented
感谢贡献，目前代码库暂不新增功能支持，PR先关闭了

2024-03-05 03:01 UTC, closed without merging