Add PoseC3D model.
PaddlePaddle/PaddleVideo pull request #446
Opened 2022-06-04 15:46 UTC by txyugood

Add PoseC3D model, please review.

2022-07-06 09:28 UTC, huangjun12 requested changes

2022-07-06 09:28 UTC, huangjun12 commented on docs/en/model_zoo/recognition/posec3d.md
> +# AGCN
名称改成PoseC3D吧

2022-07-06 09:28 UTC, huangjun12 commented on docs/zh-CN/model_zoo/recognition/posec3d.md
> +UCF-101以及预训练模型下载地址:
数据介绍部分可以详细些：
可以贴一下公开数据集的下载链接和简短介绍，再附带AIStudio下载链接

是否叫UCF-101-Skeleton好一些？

2022-07-06 09:28 UTC, huangjun12 commented on paddlevideo/loader/dataset/ucf101_skeleton.py
> +                item['frame_dir'] = item['frame_dir']
这几行似乎没做什么有用操作？

2022-07-06 09:28 UTC, huangjun12 commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +_quadruple = _ntuple(4)
这几个全局函数可以放在文件头部位置

2022-07-06 09:28 UTC, huangjun12 commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +def _combine_quadruple(a, b):
这个好像没必要写成全局函数？

2022-07-06 09:28 UTC, huangjun12 commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +def _init_lazy_if_proper(results, lazy):
和paddlevideo/loader/pipelines/augmentations_ava.py重名了？

全局函数也放文件头部吧

2022-07-06 09:28 UTC, huangjun12 commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +class RandomCrop:
这个也跟其它数据增强操作重名了，改一下命名吧

2022-07-06 09:28 UTC, huangjun12 commented on paddlevideo/modeling/backbones/resnet3d.py
> +                param.requires_grad = False
stop_gradient? paddle tensor没有requires_grad

2022-07-06 09:28 UTC, huangjun12 commented on paddlevideo/modeling/backbones/resnet3d_slowfast.py
> +class ResNet3dSlowFast(nn.Layer):
能否直接使用现成的SlowFast模型 https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/slowfast.md

2022-07-06 09:30 UTC, huangjun12 commented
1. 有部分代码格式不太标准，可以在git commit之前，pre-commit install
2. 请添加TIPC部分

2022-07-08 03:25 UTC, txyugood commented on paddlevideo/modeling/backbones/resnet3d_slowfast.py
> +class ResNet3dSlowFast(nn.Layer):
没有使用SlowFast模型，使用的是SlowOnly，无关代码移除。

2022-07-08 03:25 UTC, txyugood commented on paddlevideo/modeling/backbones/resnet3d.py
> +                param.requires_grad = False
已移除。

2022-07-08 03:25 UTC, txyugood commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +class RandomCrop:
Done.

2022-07-08 03:26 UTC, txyugood commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +def _init_lazy_if_proper(results, lazy):
Done.

2022-07-08 03:26 UTC, txyugood commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +def _combine_quadruple(a, b):
Done.

2022-07-08 03:27 UTC, txyugood commented on docs/en/model_zoo/recognition/posec3d.md
> +# AGCN
Done.

2022-07-08 03:27 UTC, txyugood commented on docs/zh-CN/model_zoo/recognition/posec3d.md
> +UCF-101以及预训练模型下载地址:
Done.

2022-07-08 03:27 UTC, txyugood commented on paddlevideo/loader/dataset/ucf101_skeleton.py
> +                item['frame_dir'] = item['frame_dir']
已移除。

2022-07-08 03:27 UTC, txyugood commented on paddlevideo/loader/pipelines/skeleton_pipeline.py
> +_quadruple = _ntuple(4)
Done.

2022-07-08 03:27 UTC, txyugood commented
TIPC已添加。

2022-07-14 07:05 UTC, huangjun12 commented
3个文件冲突了，请按pr里的提示修改一下～

2022-07-14 07:30 UTC, txyugood commented
> 3个文件冲突了，请按pr里的提示修改一下～

请问为什么我这边的pre-commit跟您那边的格式不太一样呢？

2022-07-14 07:36 UTC, huangjun12 commented
> > 3个文件冲突了，请按pr里的提示修改一下～
> 
> 请问为什么我这边的pre-commit跟您那边的格式不太一样呢？

pre-commit版本可能不太一样。但冲突不是pre-commit导致的哈。
冲突是因为其它pr和这个pr修改了同一份代码的同一个地方。
修复方式就是在其它pr修改的基础之上，加上这个pr的修改。

2022-07-14 07:38 UTC, huangjun12 commented
> > 3个文件冲突了，请按pr里的提示修改一下～
> 
> 请问为什么我这边的pre-commit跟您那边的格式不太一样呢？

pre-commit使用这个就ok了，https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/contribute/how_to_contribute.md#124-使用-pre-commit-勾子

2022-07-14 08:24 UTC, txyugood commented
已提交。

2022-07-14 08:32 UTC, txyugood commented
Tipc需要的数据是不是要您那边上传一下？

2022-07-14 08:34 UTC, huangjun12 commented
> Tipc需要的数据是不是要您那边上传一下？

可以的，方便给下链接吗

2022-07-14 08:38 UTC, txyugood commented
> > Tipc需要的数据是不是要您那边上传一下？
> 
> 可以的，方便给下链接吗

链接: https://pan.baidu.com/s/1-ZgyIBUA6orTHtL8r9zCqw 
提取码: o24c

2022-07-14 09:34 UTC, huangjun12 commented
> > > Tipc需要的数据是不是要您那边上传一下？
> > 
> > 
> > 可以的，方便给下链接吗
> 
> 链接: https://pan.baidu.com/s/1-ZgyIBUA6orTHtL8r9zCqw 提取码: o24c

https://videotag.bj.bcebos.com/PaddleVideo-release2.3/PoseC3D_data_small.tar

2022-07-14 09:40 UTC, txyugood commented
已添加tipc测试数据下载链接。

2022-08-04 05:56 UTC, huangjun12 commented
LGTM

2022-08-04 05:56 UTC, merged