efficient gcn
PaddlePaddle/PaddleVideo pull request #506
Opened 2022-08-13 04:09 UTC by Wuxiao85

efficient gcn pr

2022-08-13 04:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleVideo?pullRequest=506) before we can accept your contribution.<br/><hr/>**ubuntu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleVideo?pullRequest=506) it.</sub>

2022-08-17 08:40 UTC, huangjun12 requested changes
合入套件的代码需要重构集成一下哈，不能放在application下

2022-08-18 09:56 UTC, huangjun12 commented
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/contribute/add_new_algorithm.md 参考这个重构哈

2022-09-06 09:26 UTC, huangjun12 requested changes
1. 补充一下模型中英文文档
2. git commit之前确认安装了pre-commit
3. 代码需要自行验证跑通，并且精度达标哈。同时我们这边也会进行测试

2022-09-06 09:26 UTC, huangjun12 commented on configs/recognition/efficientgcn/efficientgcn2001.yaml
> +  train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
check下，数据处理过程 和 FSD数据集上的处理一致嘛
其它模态的信息如何生成呢

2022-09-06 09:26 UTC, huangjun12 commented on configs/recognition/efficientgcn/efficientgcn2002.yaml
> +MODEL: #MODEL field
2001和2002两个配置文件的含义和区别是？

2022-09-06 09:26 UTC, huangjun12 commented on configs/recognition/efficientgcn/efficientgcn2002.yaml
> +
空格行删除吧 commit之前用了pre-commit吗

2022-09-06 09:26 UTC, huangjun12 commented on paddlevideo/loader/dataset/ntu_feeder.py
> +class NTU_Feeder(BaseDataset):
命名该成 NTUDatasest

2022-09-06 09:26 UTC, huangjun12 commented on paddlevideo/loader/dataset/ntu_feeder.py
> +class NTU_Location_Feeder():
命名改成 NTULocationDataset ？

2022-09-06 09:26 UTC, huangjun12 commented on paddlevideo/modeling/backbones/initializer.py
> +
这个文件可以删除了 参数初始化方法参考 https://github.com/PaddlePaddle/PaddleVideo/blob/4c100455a941fa31705e30a4449db8d30bdf3f02/paddlevideo/modeling/backbones/pptsm_v2.py#L310

2022-09-06 09:26 UTC, huangjun12 commented on paddlevideo/tasks/train.py
> +        places = paddle.set_device('cpu')
默认gpu吧

2022-09-19 02:46 UTC, huangjun12 commented on paddlevideo/modeling/backbones/efficient_gcnv1.py
> +def init_param(layers):
这个函数写到 EfficientGCN类里面？

2022-09-19 02:46 UTC, huangjun12 commented on paddlevideo/modeling/heads/efficientgcn_head.py
> +        return x[0]
x的第0维不是batch size吗 确定返回这个？

2022-09-19 03:49 UTC, Wuxiao85 commented on paddlevideo/modeling/heads/efficientgcn_head.py
> +        return x[0]
网络返回了最终分类结果和提取的特征，这里的x是一个dict

2022-09-19 03:49 UTC, Wuxiao85 commented on paddlevideo/modeling/heads/efficientgcn_head.py
> +        return x[0]
网络返回了预测结果和特征值，这里x是一个元组

2022-09-19 03:51 UTC, Wuxiao85 commented on configs/recognition/efficientgcn/efficientgcn2002.yaml
> +
用了的，检测通过了才提交的

2022-09-19 03:51 UTC, Wuxiao85 commented on configs/recognition/efficientgcn/efficientgcn2002.yaml
> +MODEL: #MODEL field
2001是xsub，2002是xview，对应的是论文代码里的命名特征

2022-09-19 03:52 UTC, Wuxiao85 commented on configs/recognition/efficientgcn/efficientgcn2002.yaml
> +MODEL: #MODEL field
2000是xsub，2001是xview，对应的原文代码里的命名

2022-09-19 03:58 UTC, Wuxiao85 commented on paddlevideo/modeling/backbones/efficient_gcnv1.py
> +def init_param(layers):
这个初始化是写在外面的

2022-09-19 06:53 UTC, huangjun12 commented on paddlevideo/modeling/backbones/efficient_gcnv1.py
> +def init_param(layers):
https://github.com/PaddlePaddle/PaddleVideo/blob/9ebfc8c0220ef9acf2ba6226f08610150087ca42/paddlevideo/modeling/backbones/resnet_tsm.py#L327  参考这个函数改写一下呢？

2022-10-20 03:58 UTC, huangjun12 commented
【测试结果】:
使用NTU-RGBD-60(CTR-GCN部分)数据，配置文件使用efficientgcn2001.yaml，精度结果仅有25.23，远低于预期。请修复～

2024-03-05 03:03 UTC, closed without merging

2024-03-05 03:03 UTC, jerrywgz commented
感谢贡献，目前代码库暂不新增功能支持，PR先关闭了